title: "Viá»‡t Háº£i â€“ Developer"
tagline: "Fast, clear, and minimal."
description: "Personal site of Viá»‡t Háº£i â€“ Developer & System Thinker"
url: "https://haivtv.com"
baseurl: ""

theme: jekyll-theme-chirpy

author:
  name: "Viá»‡t Háº£i"
  avatar: "/assets/img/avatar.jpg"
  bio: "ğŸ‘¨â€ğŸ’» Developer Â· ğŸ± Poolplayer"
  location: "Vietnam"
  links:
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://fb.com/haivtv"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/vtvh"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
timezone: Asia/Ho_Chi_Minh
lang: vi

