title: "Trang cÃ¡ nhÃ¢n cá»§a Viá»‡t Háº£i"
tagline: "Trang cÃ¡ nhÃ¢n nhanh, rÃµ rÃ ng vÃ  tá»‘i giáº£n."
description: "Trang cÃ¡ nhÃ¢n cá»§a Viá»‡t Háº£i â€” ğŸ‘¨â€ğŸ’» Láº­p trÃ¬nh viÃªn Â· ğŸ± NgÆ°á»i chÆ¡i bida."
url: "https://haivtv.com"
baseurl: ""

image: "/assets/img/share.jpg"

theme: jekyll-theme-chirpy

author:
  name: "Viá»‡t Háº£i"
  avatar: "/assets/img/avatar.jpg"
  bio: "ğŸ‘¨â€ğŸ’» Láº­p trÃ¬nh viÃªn Â· ğŸ± NgÆ°á»i chÆ¡i bida"
  location: "Vietnam"
  links:
    - label: "Facebook"
      icon: "fab fa-facebook"
      url: "https://fb.com/haivtv"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/vtvh"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
timezone: Asia/Ho_Chi_Minh
lang: vi

exclude:
  - .github/
  - Gemfile
  - Gemfile.lock
  - README.md

